apr = {'name': 'International Workshop on Automated Program Repair', 'acronym': 'APR', 'type': WORKSHOP}
ase = {'name': 'International Conference on Automated Software Engineering', 'acronym': 'ASE', 'type': CONFERENCE}
ast = {'name': 'International Conference on Automation of Software Test', 'acronym': 'AST', 'type': CONFERENCE}
ast = {'name': 'International Conference on Automated Software Test', 'acronym': 'AST', 'type': CONFERENCE}
ast = {'name': 'International Workshop on Automated Software Test', 'acronym': 'AST', 'type': WORKSHOP}
bs = {'name': 'BioSystems', 'acronym': 'BS', 'type': JOURNAL}
cec = {'name': 'Congress on Evolutionary Computation', 'acronym': 'CEC', 'type': BOOK_CHAPTER}
cseet = {'name': 'International Conference on Software Engineering Education and Training', 'acronym': 'CSEE\&T', 'type': CONFERENCE}
ec = {'name': 'Evolutionary Computation', 'acronym': 'EC', 'type': JOURNAL}
ese = {'name': 'Empirical Software Engineering', 'acronym': 'ESE', 'type': JOURNAL}
esecfse = {'name': 'Joint meeting of the European Software Engineering Conference and the ACM SIGSOFT Symposium on the Foundations of Software Engineering', 'acronym': 'ESEC/FSE', 'type': CONFERENCE}
esev = {'name': 'Empirical Software Engineering and Verification', 'acronym': 'ESEV', 'type': BOOK_CHAPTER}
fmt = {'name': 'Formal Methods and Testing', 'acronym': 'FMT', 'type': BOOK_CHAPTER}
gecco = {'name': 'Genetic and Evolutionary Computation Conference', 'acronym': 'GECCO', 'type': CONFERENCE}
hicss = {'name': 'International Conference on', 'acronym': 'HICSS', 'type': CONFERENCE}
ib = {'name': 'Integrative Biology', 'acronym': 'IB', 'type': JOURNAL}
icse = {'name': 'International Conference on Software Engineering', 'acronym': 'ICSE', 'type': CONFERENCE}
icse_seet = {'name': 'International Conference on Software Engineering: Software Engineering Education and Training', 'acronym': 'ICSE-SEET', 'type': CONFERENCE}
icse_seip = {'name': 'International Conference on Software Engineering — Software Engineering In Practice Track', 'acronym': 'ICSE-SEIP', 'type': CONFERENCE}
icsm = {'name': 'International Conference on Software Maintenance', 'acronym': 'ICSM', 'type': CONFERENCE}
icsme = {'name': 'International Conference on Software Maintenance and Evolution', 'acronym': 'ICSME', 'type': CONFERENCE}
icst = {'name': 'International Conference on Software Testing, Verification and Validation', 'acronym': 'ICST', 'type': CONFERENCE}
icst = {'name': 'International Conference on Software Testing, Validation and Verification', 'acronym': 'ICST', 'type': CONFERENCE}
issta = {'name': 'International Conference on Software Testing and Analysis', 'acronym': 'ISSTA', 'type': CONFERENCE}
issta = {'name': 'International Symposium on Software Testing and Analysis', 'acronym': 'ISSTA', 'type': CONFERENCE}
ist = {'name': 'Information and Software Technology', 'acronym': 'IST', 'type': JOURNAL}
jrsi = {'name': 'Journal of the Royal Society Interface', 'acronym': 'JRSI', 'type': JOURNAL}
jseet = {'name': 'International Conference on Software Engineering (ICSE) — Joint Track on Software Engineering Education and Training', 'acronym': 'JSEET', 'type': CONFERENCE}
jss = {'name': 'Journal of Systems and Software', 'acronym': 'JSS', 'type': JOURNAL}
kcse = {'name': 'Korea Conference on Software Engineering', 'acronym': 'KCSE', 'type': CONFERENCE}
mabs = {'name': 'Multi-Agent-Based Simulation XIII — International Workshop on Multi-Agent Simulation', 'acronym': 'MABS', 'type': WORKSHOP}
mutation = {'name': 'International Workshop on Mutation Analysis', 'acronym': 'Mutation', 'type': WORKSHOP}
plsone = {'name': 'PLoS ONE', 'acronym': 'PLSONE', 'type': JOURNAL}
ppig = {'name': 'Psychology of Programming Interest Group Annual Workshop', 'acronym': 'PPIG', 'type': WORKSHOP}
qsic = {'name': 'International Conference on Quality Software', 'acronym': 'QSIC', 'type': CONFERENCE}
regression = {'name': 'International Workshop on Regression Testing', 'acronym': 'Regression', 'type': WORKSHOP}
sbst = {'name': 'International Workshop on Search-Based Software Testing', 'acronym': 'SBST', 'type': WORKSHOP}
scam = {'name': 'International Working Conference on Source Code Analysis & Manipulation', 'acronym': 'SCAM', 'type': CONFERENCE}
scp = {'name': 'Science of Computer Programming', 'acronym': 'SCP', 'type': JOURNAL}
seke = {'name': 'International Conference on Software Engineering and Knowledge Engineering', 'acronym': 'SEKE', 'type': CONFERENCE}
sigcse = {'name': 'ACM SIGCSE Technical Symposium on Computer Science Education', 'acronym': 'SIGCSE', 'type': CONFERENCE}
ssbse = {'name': 'International Symposium on Search-Based Software Engineering', 'acronym': 'SSBSE', 'type': CONFERENCE}
stov = {'name': 'International Workshop on Software Test Output Validation', 'acronym': 'STOV', 'type': WORKSHOP}
stvr = {'name': 'Software Testing, Verification and Reliability', 'acronym': 'STVR', 'type': JOURNAL}
taicpart = {'name': 'Testing: Academic and Industrial Conference — Practice And Research Techniques', 'acronym': 'TAIC PART', 'type': CONFERENCE}
tcs = {'name': 'Theoretical Computer Science', 'acronym': 'TCS', 'type': JOURNAL}
tosem = {'name': 'ACM Transactions on Software Engineering and Methodology', 'acronym': 'TOSEM', 'type': JOURNAL}
tse = {'name': 'IEEE Transactions on Software Engineering', 'acronym': 'TSE', 'type': JOURNAL}
uktest = {'name': 'UK Software Testing Workshop', 'acronym': 'UKTest', 'type': WORKSHOP}
woda = {'name': 'International Workshop on Dynamic Analysis', 'acronym': 'WODA', 'type': WORKSHOP}
